---
AXIS:
  - name: "Base"
    datawidth: 512
  - name: "Word"
    datawidth: 64
AXI:
  - &BaseAxi
    name: "Base"
    addrwidth: 64
    datawidth: 512
    no_attrib: true
  - &NvmeAxi
    name: "Nvme"
    addrwidth: 32
    datawidth: 32
    no_burst: true
    no_attrib: true
  - &CtrlAxi
    name: "Ctrl"
    addrwidth: 32
    datawidth: 32
    no_burst: true
    no_attrib: true

HMem: *BaseAxi
CMemUsed: true
CMem: *BaseAxi
NVMeUsed: false
NVMe: *NvmeAxi
Ctrl: *CtrlAxi
RegMap:
  - index: 0
    name: ctrl
    offset: 0
    count: 12
  - index: 1
    name: ctrl
    offset: 0
    count: 12
---
